version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: #If you are using Yarn change this to Yarn
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build #If you are using Yarn change this to Yarn yolo
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command: 'npx cypress run'
      - build